name: Tests

on:
  push:
    branches: [ main, copilot/fix-8-2 ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]
    continue-on-error: false

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
        # Install only essential dependencies for testing
        pip install voluptuous
    
    - name: Run tests
      run: |
        pytest tests/test_const.py tests/test_integration_structure.py -v

  lint:
    runs-on: ubuntu-latest
    continue-on-error: false
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    
    - name: Install linting dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8
    
    - name: Check code formatting with black
      run: |
        black --check --diff custom_components/ tests/
    
    - name: Check import sorting with isort
      run: |
        isort --check-only --diff custom_components/ tests/
    
    - name: Lint with flake8
      run: |
        flake8